In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch

In [8]:
data = [[1, 2], [3, 4.0]]

In [9]:
x_data = torch.tensor(data)
x_data

tensor([[1., 2.],
        [3., 4.]])

In [10]:
numpy_array = np.array(data)
x_np = torch.from_numpy(numpy_array)
x_np

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [11]:
numpy_array

array([[1., 2.],
       [3., 4.]])

In [14]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [15]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [17]:
x_zeroes = torch.zeros_like(x_data)
x_zeroes

tensor([[0., 0.],
        [0., 0.]])

In [18]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [19]:
torch.zeros(4, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [20]:
torch.rand(8, 9)

tensor([[0.5613, 0.5087, 0.3415, 0.7431, 0.2852, 0.6129, 0.5286, 0.6319, 0.1121],
        [0.0515, 0.8146, 0.2254, 0.0790, 0.9580, 0.7059, 0.9990, 0.6226, 0.1528],
        [0.4996, 0.8736, 0.8547, 0.2316, 0.8026, 0.7828, 0.4683, 0.7128, 0.5627],
        [0.7830, 0.2858, 0.7257, 0.6121, 0.6333, 0.4720, 0.8312, 0.7053, 0.6428],
        [0.1954, 0.9313, 0.2100, 0.3403, 0.7780, 0.7379, 0.1141, 0.5725, 0.8770],
        [0.5914, 0.1229, 0.2942, 0.6065, 0.2012, 0.4297, 0.5649, 0.3156, 0.1954],
        [0.4604, 0.9741, 0.9787, 0.3805, 0.0600, 0.1253, 0.3304, 0.8565, 0.0027],
        [0.5833, 0.5216, 0.3607, 0.8385, 0.6499, 0.1689, 0.3432, 0.5745, 0.1610]])

In [23]:
tensor = torch.rand(4, 5)
tensor

tensor([[0.1869, 0.9025, 0.0587, 0.0910, 0.9462],
        [0.4379, 0.5585, 0.3074, 0.1569, 0.2843],
        [0.3614, 0.5531, 0.4738, 0.6191, 0.7890],
        [0.6743, 0.5176, 0.2595, 0.0721, 0.1071]])

In [24]:
tensor.shape

torch.Size([4, 5])

In [25]:
tensor.dtype

torch.float32

In [26]:
tensor.device

device(type='cpu')

In [27]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [28]:
tensor

tensor([[0.1869, 0.9025, 0.0587, 0.0910, 0.9462],
        [0.4379, 0.5585, 0.3074, 0.1569, 0.2843],
        [0.3614, 0.5531, 0.4738, 0.6191, 0.7890],
        [0.6743, 0.5176, 0.2595, 0.0721, 0.1071]])

In [29]:
tensor[:, -1]

tensor([0.9462, 0.2843, 0.7890, 0.1071])

In [9]:
x_data = [[1,2,3], [4, 5, 6], [7,8,9]]
x_data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
x_tensor = torch.tensor(x_data)
x_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
x_ones = torch.ones_like(x_tensor)
x_ones

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [18]:
x_rand = torch.rand_like(x_tensor, dtype = torch.float)
x_rand

tensor([[0.8179, 0.5158, 0.5963],
        [0.5698, 0.9020, 0.1859],
        [0.2109, 0.7268, 0.7318]])

In [21]:
shape = (2,3,)
shape

(2, 3)

In [24]:
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.9021, 0.8507, 0.2412],
        [0.1085, 0.1362, 0.3397]])

In [26]:
ones_tensor = torch.ones(shape)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [28]:
zeros_tensor = torch.zeros(shape)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
torch.rand(6,7)

tensor([[0.2818, 0.3768, 0.8450, 0.2482, 0.6989, 0.9378, 0.7797],
        [0.6198, 0.8571, 0.2394, 0.1603, 0.2169, 0.9810, 0.2872],
        [0.9571, 0.5272, 0.0185, 0.2890, 0.0692, 0.9859, 0.0695],
        [0.7169, 0.0948, 0.7652, 0.9401, 0.4689, 0.1913, 0.4024],
        [0.2874, 0.7615, 0.9917, 0.2467, 0.1586, 0.7015, 0.6122],
        [0.1804, 0.6357, 0.6877, 0.4208, 0.6624, 0.6890, 0.7129]])

In [30]:
torch.rand(9,8)

tensor([[0.0932, 0.2111, 0.5525, 0.7084, 0.6457, 0.5437, 0.9344, 0.9241],
        [0.9939, 0.9822, 0.6648, 0.4093, 0.6129, 0.2301, 0.2453, 0.4021],
        [0.4505, 0.3551, 0.1170, 0.1892, 0.6672, 0.7081, 0.3281, 0.0721],
        [0.2925, 0.9228, 0.1157, 0.8157, 0.6076, 0.2871, 0.4623, 0.0673],
        [0.6712, 0.0901, 0.9322, 0.7527, 0.5452, 0.2036, 0.4948, 0.0425],
        [0.6222, 0.6697, 0.5354, 0.5378, 0.6453, 0.6232, 0.2426, 0.5898],
        [0.4483, 0.5014, 0.5677, 0.0476, 0.6131, 0.9389, 0.0898, 0.7601],
        [0.1090, 0.4977, 0.8359, 0.9024, 0.1696, 0.2895, 0.2537, 0.0779],
        [0.3190, 0.5969, 0.7192, 0.6263, 0.8075, 0.2419, 0.5469, 0.5283]])

In [31]:
torch.ones(6, 7)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
torch.zeros(7, 9)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
tensor = torch.rand(5, 7)
tensor

tensor([[0.1882, 0.1740, 0.2225, 0.6902, 0.5143, 0.0356, 0.1898],
        [0.7189, 0.7946, 0.9036, 0.1609, 0.3311, 0.5311, 0.3742],
        [0.0186, 0.1769, 0.7262, 0.2127, 0.8777, 0.0184, 0.8275],
        [0.6489, 0.4923, 0.4399, 0.2049, 0.3851, 0.7603, 0.6382],
        [0.8630, 0.5004, 0.8998, 0.4037, 0.9083, 0.5517, 0.4393]])

In [35]:
print(f'Shape of a tensor: {tensor.shape}')
print(f'Datatype of a tensor: {tensor.dtype}')
print(f'Device type of a tensor: {tensor.device}')

Shape of a tensor: torch.Size([5, 7])
Datatype of a tensor: torch.float32
Device type of a tensor: cpu


In [37]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [38]:
tensor = torch.rand(6, 8)
tensor

tensor([[0.3176, 0.8399, 0.8422, 0.9956, 0.6695, 0.6444, 0.9754, 0.1797],
        [0.2231, 0.5802, 0.6407, 0.6637, 0.5973, 0.7044, 0.8850, 0.3223],
        [0.8912, 0.2368, 0.3079, 0.5627, 0.4011, 0.0643, 0.1935, 0.1228],
        [0.5335, 0.5676, 0.1176, 0.9042, 0.5731, 0.7794, 0.2205, 0.6155],
        [0.8613, 0.5028, 0.7334, 0.3776, 0.2502, 0.4311, 0.2739, 0.0433],
        [0.0295, 0.1474, 0.8055, 0.7355, 0.9162, 0.6803, 0.8355, 0.7974]])

In [41]:
print(f'First Row: {tensor[0]}')
print(f'First Column: {tensor[:, 0]}')
print(f'Last Column: {tensor[:, -1]}')

First Row: tensor([0.3176, 0.8399, 0.8422, 0.9956, 0.6695, 0.6444, 0.9754, 0.1797])
First Column: tensor([0.3176, 0.2231, 0.8912, 0.5335, 0.8613, 0.0295])
Last Column: tensor([0.1797, 0.3223, 0.1228, 0.6155, 0.0433, 0.7974])


In [42]:
ones = torch.ones(5, 5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [43]:
ones [:, [1, 3]]= 0

In [44]:
ones

tensor([[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]])

In [46]:
torch.cat([ones, ones], dim = 0)

tensor([[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]])

In [47]:
torch.cat([ones, ones], dim = 1)

tensor([[1., 0., 1., 0., 1., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 0., 1., 0., 1.]])

In [48]:
tensor = torch.rand(3, 5)


In [52]:
y1 = tensor @ tensor.T
y1

tensor([[2.4027, 0.7659, 2.2308],
        [0.7659, 1.1015, 0.8723],
        [2.2308, 0.8723, 2.2972]])

In [53]:
y3 = torch.rand_like(y1)
y3

tensor([[0.4051, 0.9656, 0.3748],
        [0.7115, 0.7638, 0.4456],
        [0.1630, 0.8117, 0.8822]])

In [54]:
torch.matmul(y1, y1.T, out = y3)

tensor([[11.3362,  4.6299, 11.1527],
        [ 4.6299,  2.5609,  4.6732],
        [11.1527,  4.6732, 11.0144]])

In [55]:
y3

tensor([[11.3362,  4.6299, 11.1527],
        [ 4.6299,  2.5609,  4.6732],
        [11.1527,  4.6732, 11.0144]])

In [56]:
tensor

tensor([[0.1890, 0.7824, 0.9170, 0.7714, 0.5646],
        [0.9132, 0.1940, 0.0810, 0.1473, 0.4492],
        [0.2173, 0.7744, 0.4981, 0.8864, 0.7852]])

In [57]:
z = tensor * tensor

In [59]:
z

tensor([[0.0357, 0.6121, 0.8410, 0.5951, 0.3188],
        [0.8339, 0.0376, 0.0066, 0.0217, 0.2018],
        [0.0472, 0.5997, 0.2481, 0.7857, 0.6165]])

In [60]:
z = tensor.mul(tensor)

In [61]:
z

tensor([[0.0357, 0.6121, 0.8410, 0.5951, 0.3188],
        [0.8339, 0.0376, 0.0066, 0.0217, 0.2018],
        [0.0472, 0.5997, 0.2481, 0.7857, 0.6165]])

In [62]:
tensor

tensor([[0.1890, 0.7824, 0.9170, 0.7714, 0.5646],
        [0.9132, 0.1940, 0.0810, 0.1473, 0.4492],
        [0.2173, 0.7744, 0.4981, 0.8864, 0.7852]])

In [63]:
tensor.sum()

tensor(8.1705)

In [65]:
print(f'Tensor: {tensor}')

Tensor: tensor([[0.1890, 0.7824, 0.9170, 0.7714, 0.5646],
        [0.9132, 0.1940, 0.0810, 0.1473, 0.4492],
        [0.2173, 0.7744, 0.4981, 0.8864, 0.7852]])


In [66]:
tensor.add_(5)

tensor([[5.1890, 5.7824, 5.9170, 5.7714, 5.5646],
        [5.9132, 5.1940, 5.0810, 5.1473, 5.4492],
        [5.2173, 5.7744, 5.4981, 5.8864, 5.7852]])

In [67]:
tensor.subtract_(10)

tensor([[-4.8110, -4.2176, -4.0830, -4.2286, -4.4354],
        [-4.0868, -4.8060, -4.9190, -4.8527, -4.5508],
        [-4.7827, -4.2256, -4.5019, -4.1136, -4.2148]])

In [68]:
tensor.multiply_(-1)

tensor([[4.8110, 4.2176, 4.0830, 4.2286, 4.4354],
        [4.0868, 4.8060, 4.9190, 4.8527, 4.5508],
        [4.7827, 4.2256, 4.5019, 4.1136, 4.2148]])

In [69]:
tensor

tensor([[4.8110, 4.2176, 4.0830, 4.2286, 4.4354],
        [4.0868, 4.8060, 4.9190, 4.8527, 4.5508],
        [4.7827, 4.2256, 4.5019, 4.1136, 4.2148]])

In [70]:
tensor.sub_(4)

tensor([[0.8110, 0.2176, 0.0830, 0.2286, 0.4354],
        [0.0868, 0.8060, 0.9190, 0.8527, 0.5508],
        [0.7827, 0.2256, 0.5019, 0.1136, 0.2148]])

In [76]:
t = torch.ones(5)

In [77]:
n = t.numpy()

In [78]:
t.add_(1)

tensor([2., 2., 2., 2., 2.])

In [79]:
t

tensor([2., 2., 2., 2., 2.])

In [80]:
n

array([2., 2., 2., 2., 2.], dtype=float32)

In [81]:
n = np.ones(5)

In [82]:
t = torch.from_numpy(n)

In [83]:
n

array([1., 1., 1., 1., 1.])

In [84]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)